// <auto-generated />
namespace App_Market_API_integration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201701131407288_DataMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
